In [1]:
import plotly.graph_objs as go
import plotly.express as px
import pandas as pd
from plotly import colors

- Import needed libaries

In [2]:
df = pd.read_csv('riaakaggle.csv') # import file
df = df.head(n=50) # take first 50 entries
df

,Unnamed: 0,Artist,Certified Units,Gold,Platinum,Multi-Platinum,Diamond
0,0,THE BEATLES,183.0,48,42,26,6
1,1,GARTH BROOKS,157.0,31,31,17,9
2,2,ELVIS PRESLEY,139.0,101,57,25,1
3,3,EAGLES,120.0,13,13,11,3
4,4,LED ZEPPELIN,111.5,19,18,14,5
5,5,MICHAEL JACKSON,85.0,15,13,9,2
6,6,BILLY JOEL,84.5,18,17,13,2
7,7,ELTON JOHN,79.0,38,28,14,1
8,8,AC/DC,75.0,22,20,12,1
9,9,PINK FLOYD,75.0,19,15,12,2
10,10,GEORGE STRAIT,69.0,39,33,13,0
11,11,BARBRA STREISAND,68.5,51,30,12,0
12,12,AEROSMITH,66.5,25,18,12,1
13,13,MARIAH CAREY,66.5,16,13,10,2
14,14,THE ROLLING STONES,66.5,43,28,11,1
15,15,BRUCE SPRINGSTEEN,65.5,22,17,11,2
16,16,MADONNA,64.5,20,17,12,2
17,17,METALLICA,63.0,13,13,11,1
18,18,WHITNEY HOUSTON,60.0,11,9,7,3
19,19,VAN HALEN,56.5,14,13,12,2
20,20,FLEETWOOD MAC,54.5,14,9,8,1
21,21,CELINE DION,51.0,13,11,8,2
22,22,U2,51.0,16,16,11,1
23,23,NEIL DIAMOND,49.5,40,21,12,0
24,24,JOURNEY,49.0,13,11,9,2
25,25,KENNY G,48.0,15,11,8,1
26,26,SHANIA TWAIN,48.0,5,5,4,3
27,27,KENNY ROGERS,47.5,28,17,7,1
28,28,ALABAMA,46.5,23,20,10,0
29,29,EMINEM,46.5,12,9,8,2
30,30,TAYLOR SWIFT,46.0,9,9,7,1
31,31,BOB SEGER & THE SILVER BULLET BAND,44.5,14,13,7,1
32,32,GUNS N' ROSES,44.5,8,7,5,1
33,33,ALAN JACKSON,43.5,18,15,8,0
34,34,SANTANA,43.5,21,10,7,1
35,35,QUEEN,43.0,20,12,8,0
36,36,REBA MC ENTIRE,41.0,27,19,9,0
37,37,ERIC CLAPTON,40.0,23,11,7,1
38,38,CHICAGO,38.5,23,18,8,0
39,39,SIMON & GARFUNKEL,38.5,12,11,7,1
40,40,FOREIGNER,38.0,11,9,7,0
41,41,ROD STEWART,38.0,27,19,10,0
42,42,TIM MCGRAW,37.5,14,11,9,0
43,43,BACKSTREET BOYS,37.0,5,5,3,2
44,44,2 PAC,36.5,10,9,6,2
45,45,BOB DYLAN,36.0,33,15,6,0
46,46,DEF LEPPARD,35.5,11,8,5,2
47,47,BON JOVI,34.5,14,11,5,1
48,48,BRITNEY SPEARS,34.5,9,8,4,2
49,49,DAVE MATTHEWS BAND,34.5,17,14,7,0

- File is sortend on certified units, take first 50

In [3]:
x_axis = df['Artist']

data = [
    go.bar(x=x_axis, y=df['Certified Units']),
    go.bar(x=x_axis, y=df['Gold']),
    go.bar(x=x_axis, y=df['Platinum']),
    go.bar(x=x_axis, y=df['Multi-Platinum']),
    go.bar(x=x_axis, y=df['Diamond'])
]

layout = go.Layout(
    title='Percentage unmarried in the US between 25 and 34 by income',
    height=400,
    xaxis=go.layout.XAxis(
        type='category', # the type for the x axis is categorical
        title='Artist',    # x-axis title
        tickangle=0,    # change label to horizontal
        tickfont=dict(size=10) # change label size
    ),
    yaxis=go.layout.YAxis(
        tickformat=',.0%', # show as percentage
        title='Albums' # y-axis title
    )
)

fig = go.Figure(data=data, layout=layout)
fig.show()

TypeError: 'module' object is not callable